version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=parcel-password
      - POSTGRES_USER=parcel-api
      - POSTGRES_DB=parcel